from __future__ import annotations

from typing import Literal, TypedDict


SkillCategory = Literal[
    "technical_skills",
    "platforms_cloud",
    "tooling_devops",
    "competencies",
    "role_descriptors",
    "soft_skills",
]


class SkillMeta(TypedDict):
    display_name: str
    aliases: list[str]
    skill_groups: list[str]
    prerequisites: list[str]
    related_skills: list[str]
    specializations: list[str]
    classification_target: SkillCategory


SKILL_TAXONOMY: dict[str, SkillMeta] = {
    "python": {
        "display_name": "Python",
        "aliases": ["python"],
        "skill_groups": ["backend", "data", "ai_ml"],
        "prerequisites": [],
        "related_skills": ["fastapi", "airflow", "dbt"],
        "specializations": ["programming_language"],
        "classification_target": "technical_skills",
    },
    "rust": {
        "display_name": "Rust",
        "aliases": ["rust"],
        "skill_groups": ["backend"],
        "prerequisites": [],
        "related_skills": ["docker"],
        "specializations": ["programming_language"],
        "classification_target": "technical_skills",
    },
    "java": {
        "display_name": "Java",
        "aliases": ["java"],
        "skill_groups": ["backend"],
        "prerequisites": [],
        "related_skills": ["docker"],
        "specializations": ["programming_language"],
        "classification_target": "technical_skills",
    },
    "golang": {
        "display_name": "GoLang",
        "aliases": ["golang", "go"],
        "skill_groups": ["backend"],
        "prerequisites": [],
        "related_skills": ["docker"],
        "specializations": ["programming_language"],
        "classification_target": "technical_skills",
    },
    "fastapi": {
        "display_name": "FastAPI",
        "aliases": ["fastapi"],
        "skill_groups": ["backend"],
        "prerequisites": ["python", "rest_api"],
        "related_skills": ["docker", "postgresql"],
        "specializations": ["python_backend_framework"],
        "classification_target": "technical_skills",
    },
    "react": {
        "display_name": "React",
        "aliases": ["react", "reactjs"],
        "skill_groups": ["frontend"],
        "prerequisites": ["javascript"],
        "related_skills": ["typescript", "nextjs", "ssr"],
        "specializations": ["frontend_framework"],
        "classification_target": "technical_skills",
    },
    "nextjs": {
        "display_name": "Next.js",
        "aliases": ["next.js", "nextjs"],
        "skill_groups": ["frontend"],
        "prerequisites": ["react", "javascript"],
        "related_skills": ["typescript", "ssr"],
        "specializations": ["frontend_framework"],
        "classification_target": "technical_skills",
    },
    "typescript": {
        "display_name": "TypeScript",
        "aliases": ["typescript", "ts"],
        "skill_groups": ["frontend", "backend"],
        "prerequisites": ["javascript"],
        "related_skills": ["react", "nextjs"],
        "specializations": ["typed_javascript"],
        "classification_target": "technical_skills",
    },
    "javascript": {
        "display_name": "JavaScript",
        "aliases": ["javascript", "js"],
        "skill_groups": ["frontend", "backend"],
        "prerequisites": [],
        "related_skills": ["typescript", "react", "nextjs", "node_js"],
        "specializations": ["programming_language"],
        "classification_target": "technical_skills",
    },
    "node_js": {
        "display_name": "Node.js",
        "aliases": ["node.js", "nodejs", "node"],
        "skill_groups": ["backend", "frontend"],
        "prerequisites": ["javascript"],
        "related_skills": ["typescript", "docker"],
        "specializations": ["javascript_runtime"],
        "classification_target": "technical_skills",
    },
    "postgresql": {
        "display_name": "PostgreSQL",
        "aliases": ["postgresql", "postgres", "postgre sql"],
        "skill_groups": ["database"],
        "prerequisites": ["sql"],
        "related_skills": ["docker", "dbt", "fastapi"],
        "specializations": ["relational_database"],
        "classification_target": "technical_skills",
    },
    "mysql": {
        "display_name": "MySQL",
        "aliases": ["mysql"],
        "skill_groups": ["database"],
        "prerequisites": ["sql"],
        "related_skills": ["postgresql"],
        "specializations": ["relational_database"],
        "classification_target": "technical_skills",
    },
    "sql": {
        "display_name": "SQL",
        "aliases": ["sql", "structured query language"],
        "skill_groups": ["database", "data"],
        "prerequisites": [],
        "related_skills": ["postgresql", "mysql", "dbt"],
        "specializations": ["query_language"],
        "classification_target": "technical_skills",
    },
    "docker": {
        "display_name": "Docker",
        "aliases": ["docker"],
        "skill_groups": ["devops"],
        "prerequisites": [],
        "related_skills": ["fastapi", "postgresql", "neo4j", "containerization"],
        "specializations": ["container_platform"],
        "classification_target": "tooling_devops",
    },
    "containerization": {
        "display_name": "Containerization",
        "aliases": ["containerization", "containerization technologies"],
        "skill_groups": ["devops"],
        "prerequisites": [],
        "related_skills": ["docker", "ci_cd"],
        "specializations": ["delivery_practice"],
        "classification_target": "tooling_devops",
    },
    "rest_api": {
        "display_name": "REST API",
        "aliases": ["rest api", "restful api", "restful apis", "rest apis"],
        "skill_groups": ["backend"],
        "prerequisites": [],
        "related_skills": ["fastapi"],
        "specializations": ["api_design"],
        "classification_target": "technical_skills",
    },
    "airflow": {
        "display_name": "Airflow",
        "aliases": ["airflow", "apache airflow"],
        "skill_groups": ["data"],
        "prerequisites": ["python"],
        "related_skills": ["dbt", "sql"],
        "specializations": ["orchestration"],
        "classification_target": "technical_skills",
    },
    "dbt": {
        "display_name": "dbt",
        "aliases": ["dbt"],
        "skill_groups": ["data"],
        "prerequisites": ["sql"],
        "related_skills": ["airflow", "postgresql"],
        "specializations": ["data_transformation"],
        "classification_target": "technical_skills",
    },
    "ssr": {
        "display_name": "SSR",
        "aliases": ["ssr", "server side rendering"],
        "skill_groups": ["frontend"],
        "prerequisites": ["react"],
        "related_skills": ["nextjs", "typescript"],
        "specializations": ["rendering_strategy"],
        "classification_target": "technical_skills",
    },
    "git": {
        "display_name": "Git",
        "aliases": ["git"],
        "skill_groups": ["devops"],
        "prerequisites": [],
        "related_skills": ["version_control", "docker"],
        "specializations": ["version_control"],
        "classification_target": "tooling_devops",
    },
    "version_control": {
        "display_name": "Version Control",
        "aliases": ["version control", "version control systems"],
        "skill_groups": ["devops"],
        "prerequisites": [],
        "related_skills": ["git", "ci_cd"],
        "specializations": ["version_control"],
        "classification_target": "tooling_devops",
    },
    "ci_cd": {
        "display_name": "CI/CD",
        "aliases": ["ci/cd", "ci/cd pipelines", "ci cd", "continuous integration", "continuous delivery"],
        "skill_groups": ["devops"],
        "prerequisites": [],
        "related_skills": ["docker", "version_control"],
        "specializations": ["delivery_pipeline"],
        "classification_target": "tooling_devops",
    },
    "neo4j": {
        "display_name": "Neo4j",
        "aliases": ["neo4j"],
        "skill_groups": ["database", "data"],
        "prerequisites": ["sql"],
        "related_skills": ["postgresql", "python"],
        "specializations": ["graph_database"],
        "classification_target": "technical_skills",
    },
    "aws": {
        "display_name": "AWS",
        "aliases": ["aws", "amazon web services"],
        "skill_groups": ["cloud"],
        "prerequisites": [],
        "related_skills": ["docker", "ci_cd"],
        "specializations": ["cloud_platform"],
        "classification_target": "platforms_cloud",
    },
    "gcp": {
        "display_name": "GCP",
        "aliases": ["gcp", "google cloud platform"],
        "skill_groups": ["cloud"],
        "prerequisites": [],
        "related_skills": ["docker", "ci_cd"],
        "specializations": ["cloud_platform"],
        "classification_target": "platforms_cloud",
    },
    "azure": {
        "display_name": "Azure",
        "aliases": ["azure", "microsoft azure"],
        "skill_groups": ["cloud"],
        "prerequisites": [],
        "related_skills": ["docker", "ci_cd"],
        "specializations": ["cloud_platform"],
        "classification_target": "platforms_cloud",
    },
    "android": {
        "display_name": "Android",
        "aliases": ["android", "android development"],
        "skill_groups": ["mobile"],
        "prerequisites": [],
        "related_skills": ["java"],
        "specializations": ["mobile_platform"],
        "classification_target": "technical_skills",
    },
    "ios": {
        "display_name": "iOS",
        "aliases": ["ios", "ios development"],
        "skill_groups": ["mobile"],
        "prerequisites": [],
        "related_skills": [],
        "specializations": ["mobile_platform"],
        "classification_target": "technical_skills",
    },
    "software_development": {
        "display_name": "Software Development",
        "aliases": ["software development"],
        "skill_groups": [],
        "prerequisites": [],
        "related_skills": [],
        "specializations": ["engineering_capability"],
        "classification_target": "competencies",
    },
    "full_stack_development": {
        "display_name": "Full-stack Development",
        "aliases": ["full-stack development", "full stack development", "full-stack"],
        "skill_groups": [],
        "prerequisites": [],
        "related_skills": [],
        "specializations": ["engineering_capability"],
        "classification_target": "competencies",
    },
    "back_end_development": {
        "display_name": "Back-end Development",
        "aliases": ["back-end development", "backend development", "back end development"],
        "skill_groups": [],
        "prerequisites": [],
        "related_skills": [],
        "specializations": ["engineering_capability"],
        "classification_target": "competencies",
    },
    "scalable_software_systems": {
        "display_name": "Scalable Software Systems",
        "aliases": ["scalable software systems", "scalable applications"],
        "skill_groups": [],
        "prerequisites": [],
        "related_skills": [],
        "specializations": ["engineering_capability"],
        "classification_target": "competencies",
    },
    "agile_environments": {
        "display_name": "Agile Environments",
        "aliases": ["agile environments", "agile"],
        "skill_groups": [],
        "prerequisites": [],
        "related_skills": [],
        "specializations": ["delivery_context"],
        "classification_target": "competencies",
    },
    "modern_development_tools": {
        "display_name": "Modern Development Tools",
        "aliases": ["modern development tools"],
        "skill_groups": [],
        "prerequisites": [],
        "related_skills": [],
        "specializations": ["delivery_context"],
        "classification_target": "competencies",
    },
    "distributed_collaboration": {
        "display_name": "Distributed Collaboration",
        "aliases": [
            "distributed teams",
            "distributed setting",
            "remote collaboration",
            "remote teams",
        ],
        "skill_groups": [],
        "prerequisites": [],
        "related_skills": [],
        "specializations": ["work_mode"],
        "classification_target": "role_descriptors",
    },
    "cross_functional_teamwork": {
        "display_name": "Cross-functional Teamwork",
        "aliases": [
            "cross-functional teamwork",
            "cross-functional team members",
            "cross-functional work",
            "cross-functional remote teams",
            "cross-functional teams",
        ],
        "skill_groups": [],
        "prerequisites": [],
        "related_skills": [],
        "specializations": ["team_topology"],
        "classification_target": "role_descriptors",
    },
}


def build_alias_index() -> dict[str, str]:
    alias_index: dict[str, str] = {}
    for canonical, meta in SKILL_TAXONOMY.items():
        alias_index[canonical] = canonical
        for alias in meta["aliases"]:
            alias_index[alias.lower()] = canonical
    return alias_index


SKILL_ALIAS_INDEX = build_alias_index()
